name: Bump

on:
  push:
    branches: [ main ]

jobs:
  bump:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[major]') ||
      contains(github.event.head_commit.message, '[minor]') ||
      contains(github.event.head_commit.message, '[patch]')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Bump version
      id: bump-version
      uses: phips28/gh-action-bump-version@v11.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag-prefix: 'v'
        major-wording: '[major]'
        minor-wording: '[minor]'
        patch-wording: '[patch]'
        skip-tag: true
        skip-commit: true
        skip-push: true

    - name: Create Pull Request
      if: steps.bump-version.outputs.newTag != ''
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{ steps.bump-version.outputs.newTag }}
        base: main
        title: "Release ${{ steps.bump-version.outputs.newTag }}"
        body: |
          ## Release ${{ steps.bump-version.outputs.newTag }}

          This PR contains the version bump for the next release.

          **Changes:**
          - Bump version to ${{ steps.bump-version.outputs.newTag }}

          **Next steps:**
          - Review and merge this PR
          - The release workflow will automatically create a tag, GitHub release, and publish the extension
        commit-message: "release: bump version to ${{ steps.bump-version.outputs.newTag }}"
        delete-branch: true
