name: Version Bump

on:
  push:
    branches: [ main ]

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version
      id: bump-version
      uses: phips28/gh-action-bump-version@master
      with:
        tag-prefix: 'v'
        major-wording: '[major]'
        minor-wording: '[minor]'
        patch-wording: '[patch]'
        skip-tag: true
        skip-commit: true
        skip-push: true

    - name: Create Pull Request
      if: steps.bump-version.outputs.newTag != ''
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{ steps.bump-version.outputs.newTag }}
        base: main
        title: "Release ${{ steps.bump-version.outputs.newTag }}"
        body: |
          ## Release ${{ steps.bump-version.outputs.newTag }}

          This PR contains the version bump for the next release.

          **Changes:**
          - Bump version to ${{ steps.bump-version.outputs.newTag }}

          **Next steps:**
          - Review and merge this PR
          - The release workflow will automatically create a tag, GitHub release, and publish the extension
        commit-message: "chore: bump version to ${{ steps.bump-version.outputs.newTag }}"
        delete-branch: true
